export const SPECIALTY_OPTIONS = [
  'Tim mạch',
  'Nội tiết - Ðái tháo đường',
  'Ung bướu',
  'Hô hấp',
  'Truyền nhiễm',
  'Ký sinh trùng',
  'HIV/AIDS',
  'Da liễu',
  'STDs',
  'Thận học',
  'Thần kinh',
  'Trạm y tế',
  'Huyết học - Truyền máu',
  'Nhi khoa',
  'Sản phụ khoa',
  'Nhiễm khuẩn học - Vi sinh',
  'Phục hồi chức năng',
  'Dược học - Dược lâm sàng',
  'Dinh dưỡng',
  'Tâm thần - Nghiện chất',
  'Y học cổ truyền',
  'Pháp y',
  'Nhãn khoa',
  'Tiết niệu',
  'Gây mê hồi sức',
  'Ngoại khoa - Ghép tạng',
  'Y tế công cộng - Dự phòng',
  'Cấp cứu - Sơ cứu',
] as const
