from collections.abc import AsyncGenerator

from sqlalchemy import text
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.core.config import settings
from app.models import Base

engine = create_async_engine(
    settings.database_url,
    pool_size=settings.DB_POOL_SIZE,
    max_overflow=settings.DB_MAX_OVERFLOW,
    echo=settings.DEBUG,
    future=True,
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False,
)


async def get_db_session() -> AsyncGenerator[AsyncSession, None]:
    """Dependency that provides an async database session per request."""
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


async def init_db_schema() -> None:
    """Create database tables if they do not exist."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def migrate_auth_schema_to_single_role() -> None:
    """
    Normalize auth schema to single-table RBAC on `users.role`.

    This keeps startup idempotent when code previously used roles/user_roles.
    """
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS role VARCHAR(20)
                NOT NULL DEFAULT 'viewer'
                """
            )
        )
        await conn.execute(
            text(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'user_roles'
                    )
                    AND EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'roles'
                    ) THEN
                        UPDATE users AS u
                        SET role = r.name
                        FROM user_roles AS ur
                        JOIN roles AS r ON r.role_id = ur.role_id
                        WHERE u.user_id = ur.user_id
                          AND r.name IN ('admin', 'editor', 'viewer');
                    END IF;
                END $$;
                """
            )
        )
        await conn.execute(text("DROP TABLE IF EXISTS user_roles"))
        await conn.execute(text("DROP TABLE IF EXISTS roles"))


async def migrate_organization_schema() -> None:
    """Add tenant organization scope and normalize roles to admin/user."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS organizations (
                    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slug VARCHAR(120) NOT NULL UNIQUE,
                    name VARCHAR(255) NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                )
                """
            )
        )
        await conn.execute(
            text(
                """
                INSERT INTO organizations (slug, name, is_active)
                VALUES ('soyte', 'soyte', TRUE), ('namkhoa', 'namkhoa', TRUE)
                ON CONFLICT (slug) DO NOTHING
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS organization_id BIGINT
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE guidelines
                ADD COLUMN IF NOT EXISTS organization_id BIGINT
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE documents
                ADD COLUMN IF NOT EXISTS organization_id BIGINT
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE chunks
                ADD COLUMN IF NOT EXISTS organization_id BIGINT
                """
            )
        )
        await conn.execute(
            text(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'ck_users_role'
                          AND conrelid = 'users'::regclass
                    ) THEN
                        ALTER TABLE users DROP CONSTRAINT ck_users_role;
                    END IF;
                END $$;
                """
            )
        )
        await conn.execute(
            text(
                """
                UPDATE users
                SET role = CASE
                    WHEN lower(coalesce(role, '')) = 'admin' THEN 'admin'
                    ELSE 'user'
                END
                """
            )
        )
        await conn.execute(text("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'"))
        await conn.execute(text("ALTER TABLE users ALTER COLUMN role SET NOT NULL"))
        await conn.execute(
            text(
                """
                ALTER TABLE users
                ADD CONSTRAINT ck_users_role CHECK (role IN ('admin', 'user'))
                """
            )
        )
        await conn.execute(
            text(
                """
                WITH default_org AS (
                    SELECT organization_id
                    FROM organizations
                    WHERE slug = 'soyte'
                    LIMIT 1
                )
                UPDATE users
                SET organization_id = (SELECT organization_id FROM default_org)
                WHERE role = 'user'
                  AND organization_id IS NULL
                """
            )
        )
        await conn.execute(
            text(
                """
                UPDATE users
                SET organization_id = NULL
                WHERE role = 'admin'
                """
            )
        )
        await conn.execute(
            text(
                """
                WITH default_org AS (
                    SELECT organization_id
                    FROM organizations
                    WHERE slug = 'soyte'
                    LIMIT 1
                )
                UPDATE guidelines
                SET organization_id = (SELECT organization_id FROM default_org)
                WHERE organization_id IS NULL
                """
            )
        )
        await conn.execute(
            text(
                """
                UPDATE documents AS d
                SET organization_id = g.organization_id
                FROM guideline_versions AS v
                JOIN guidelines AS g ON g.guideline_id = v.guideline_id
                WHERE d.version_id = v.version_id
                  AND d.organization_id IS NULL
                """
            )
        )
        await conn.execute(
            text(
                """
                UPDATE chunks AS c
                SET organization_id = g.organization_id
                FROM guideline_versions AS v
                JOIN guidelines AS g ON g.guideline_id = v.guideline_id
                WHERE c.version_id = v.version_id
                  AND c.organization_id IS NULL
                """
            )
        )
        await conn.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_users_organization_id
                ON users (organization_id)
                """
            )
        )
        await conn.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_guidelines_organization_id
                ON guidelines (organization_id)
                """
            )
        )
        await conn.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_documents_organization_id
                ON documents (organization_id)
                """
            )
        )
        await conn.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_chunks_organization_id
                ON chunks (organization_id)
                """
            )
        )
        for table_name in ("users", "guidelines", "documents", "chunks"):
            constraint_name = f"fk_{table_name}_organization_id"
            await conn.execute(
                text(
                    f"""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = '{constraint_name}'
                              AND conrelid = '{table_name}'::regclass
                        ) THEN
                            ALTER TABLE {table_name}
                            ADD CONSTRAINT {constraint_name}
                            FOREIGN KEY (organization_id)
                            REFERENCES organizations(organization_id)
                            ON DELETE RESTRICT;
                        END IF;
                    END $$;
                    """
                )
            )


async def migrate_sections_quality_schema() -> None:
    """Add minimal quality/page columns for section-level FE highlighting."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS page_start INTEGER
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS page_end INTEGER
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS start_y DOUBLE PRECISION
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS end_y DOUBLE PRECISION
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS match_score DOUBLE PRECISION
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS is_suspect BOOLEAN
                NOT NULL DEFAULT FALSE
                """
            )
        )


async def migrate_sections_enriched_schema() -> None:
    """Add richer OCR/TOC metadata columns for section-level grounding."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS node_id TEXT
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS intro_content TEXT
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS heading_bbox JSONB
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS content_bboxes JSONB
                """
            )
        )
        await conn.execute(
            text(
                """
                ALTER TABLE sections
                ADD COLUMN IF NOT EXISTS landing_chunks JSONB
                """
            )
        )


async def migrate_guidelines_ten_benh_schema() -> None:
    """Add optional disease-name column for guideline metadata."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE guidelines
                ADD COLUMN IF NOT EXISTS ten_benh TEXT
                """
            )
        )


async def migrate_chunks_text_abstract_schema() -> None:
    """Add LLM summary column for chunk retrieval payloads."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE chunks
                ADD COLUMN IF NOT EXISTS text_abstract TEXT
                """
            )
        )


async def migrate_documents_pipeline_mode_schema() -> None:
    """Add pipeline-mode metadata for uploaded documents."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE documents
                ADD COLUMN IF NOT EXISTS pipeline_mode_used VARCHAR(30)
                """
            )
        )


async def migrate_documents_original_filename_schema() -> None:
    """Preserve the user-uploaded PDF filename so the OCR pipeline can pass it verbatim to the partner core (matches local CLI behaviour)."""
    async with engine.begin() as conn:
        await conn.execute(
            text(
                """
                ALTER TABLE documents
                ADD COLUMN IF NOT EXISTS original_filename TEXT
                """
            )
        )
