ROLE_ADMIN = "admin"
ROLE_HEALTH_DEPARTMENT = "health_department"
ROLE_CENTRAL_HOSPITAL = "central_hospital"
ROLE_HOSPITAL = "hospital"
ROLE_HEALTH_STATION = "health_station"
ROLE_DOCTOR = "doctor"

ALL_ROLES: tuple[str, ...] = (
    ROLE_ADMIN,
    ROLE_HEALTH_DEPARTMENT,
    ROLE_CENTRAL_HOSPITAL,
    ROLE_HOSPITAL,
    ROLE_HEALTH_STATION,
    ROLE_DOCTOR,
)

DOCUMENT_MANAGER_ROLES: tuple[str, ...] = (
    ROLE_HEALTH_DEPARTMENT,
    ROLE_CENTRAL_HOSPITAL,
    ROLE_HOSPITAL,
    ROLE_HEALTH_STATION,
    ROLE_ADMIN,
)

ACCOUNT_MANAGER_ROLES: tuple[str, ...] = DOCUMENT_MANAGER_ROLES

TOP_LEVEL_UNIT_ROLES: tuple[str, ...] = (
    ROLE_HEALTH_DEPARTMENT,
    ROLE_CENTRAL_HOSPITAL,
)

CHILD_ROLES_BY_CREATOR: dict[str, tuple[str, ...]] = {
    ROLE_HEALTH_DEPARTMENT: (ROLE_HOSPITAL, ROLE_HEALTH_STATION),
    ROLE_CENTRAL_HOSPITAL: (ROLE_DOCTOR,),
    ROLE_HOSPITAL: (ROLE_DOCTOR,),
    ROLE_HEALTH_STATION: (ROLE_DOCTOR,),
}

PARENT_ROLES_BY_ROLE: dict[str, tuple[str, ...]] = {
    ROLE_HOSPITAL: (ROLE_HEALTH_DEPARTMENT,),
    ROLE_HEALTH_STATION: (ROLE_HEALTH_DEPARTMENT,),
    ROLE_DOCTOR: (ROLE_CENTRAL_HOSPITAL, ROLE_HOSPITAL, ROLE_HEALTH_STATION),
}
